/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#a8cbe7",
        "surface-container-low": "#f3f3f4",
        "secondary-container": "#d3e2ed",
        "on-tertiary-fixed-variant": "#274a62",
        "on-surface": "#1a1c1c",
        "background": "#f9f9f9",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#bac9d3",
        "error": "#ba1a1a",
        "on-primary-container": "#fffdff",
        "tertiary": "#3e6079",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fefdff",
        "secondary-fixed": "#d6e5ef",
        "secondary": "#526069",
        "surface-container-high": "#e8e8e8",
        "outline": "#717783",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-fixed": "#001e2f",
        "on-primary-fixed": "#001c3a",
        "on-secondary-fixed": "#0f1d25",
        "tertiary-fixed": "#c9e6ff",
        "primary": "#005dac",
        "on-primary": "#ffffff",
        "surface-dim": "#dadada",
        "outline-variant": "#c1c6d4",
        "surface": "#f9f9f9",
        "on-secondary-fixed-variant": "#3b4951",
        "surface-tint": "#005faf",
        "primary-fixed": "#d4e3ff",
        "primary-container": "#1976d2",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#577993",
        "inverse-on-surface": "#f0f1f1",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3131",
        "on-background": "#1a1c1c",
        "inverse-primary": "#a5c8ff",
        "on-surface-variant": "#414752",
        "primary-fixed-dim": "#a5c8ff",
        "on-secondary-container": "#56656e",
        "on-primary-fixed-variant": "#004786",
        "surface-bright": "#f9f9f9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["10px", {"lineHeight": "12px", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};